name = "db-website-api"
compatibility_date = "2023-12-01"

[vars]

PUBLIC_SUPABASE_URL = "https://your-supabase-project.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "public-anon-key"
API_BASE = "https://api.example.com"

SUPABASE_URL = "https://taejvzqmlswbgsknthxz.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZWp2enFtbHN3Ymdza250aHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTE3NjIsImV4cCI6MjA3MjkyNzc2Mn0.nFWly256mUiFAvAEWdvLA9n_DaNXOnV3MtMLXmHIKGc"

# Falls du Discord OAuth über Worker laufen lassen willst, brauchst du zusätzlich:
DISCORD_CLIENT_ID = "1414567063221178429"
DISCORD_CLIENT_SECRET = "5f065bc8568f6d3a030d054b82c6cba7d999c080ff2de485aadc2d77bfc9a167"
DISCORD_REDIRECT_URI = "https://op-item-db.pages.dev/callback" 

# Beispiel KV für Caching (optional)
[[kv_namespaces]]
binding = "ITEM_CACHE"

id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
preview_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

