name = "db-website-api"
compatibility_date = "2023-12-01"
pages_build_output_dir = "./public"

[vars]
PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "public-anon-key"
API_BASE = "https://api.example.com"
SUPABASE_URL = "{{ secret:SUPABASE_URL }}"
SUPABASE_ANON_KEY = "{{ secret:SUPABASE_ANON_KEY }}"
DISCORD_CLIENT_ID = "{{ secret:DISCORD_CLIENT_ID }}"
DISCORD_CLIENT_SECRET = "{{ secret:DISCORD_CLIENT_SECRET }}"
DISCORD_REDIRECT_URI = "{{ secret:DISCORD_REDIRECT_URI }}"

# Configure the sensitive values above via Wrangler secrets:
#   wrangler secret put SUPABASE_URL
#   wrangler secret put SUPABASE_ANON_KEY
#   wrangler secret put DISCORD_CLIENT_ID
#   wrangler secret put DISCORD_CLIENT_SECRET
#   wrangler secret put DISCORD_REDIRECT_URI

[[kv_namespaces]]
binding = "ITEM_CACHE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
preview_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
