name = "db-website-api"
compatibility_date = "2023-12-01"

[vars]
SUPABASE_URL = "https://your-supabase-project.supabase.co"
SUPABASE_ANON_KEY = "public-anon-key"

[[kv_namespaces]]
binding = "ITEM_CACHE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
